---
- name: Playbook description
  hosts: localhost
  tasks:
  - name: Install Apache on Ubuntu Server
    when: ansible_os_family == "Ubuntu"
    apt-get:
     name: apache2
     state: present
  - name: Install Apache on CentOS Server
    when: ansible_os_family == "RedHat"
    yum:
     name: httpd
     state: present     