---
- name: Copy file from local to remote clients
  hosts: all

  tasks:
  - name: Copying file
    become: true
    copy:
     src: /home/ganislp/some.cfg
     dest: /tmp
     owner: ganislp
     group: ganislp
     mode: 0644