---
- name: Setup httpd and open firewall port
  hosts: all

  tasks: 
  - name: Install apache packages
    apt:
     name: apache2
     state: present
    tags: i-apache2 
  - name: start apache2
    service:
     name: apache2
     state:  started  
    notify:
    - Restart apache
    tags: apache2-s
  - name:  Open port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: enabled
  - name:   Restart firwalld service to load firewall changes
    service:
     name: firewalld
     state: reloaded
  handlers:
    - name: Restart apache
      service:
       name: apache2
       state: restarted   

