---
- name: Install and Running apache
  hosts: localhost
  
  tasks:
  - name: Install apache 
    yum:
     name: httpd
     state: prescent

  - name: start httpd
    service:
      name: httpd
      state: started     

