---
- name: Install some packages
  hosts: all
  vars: 
   pack: apache2

  tasks:
  - name: Package Install
    apt: 
     name: "{{ pack }}"
     state: present
  - name: Start service
    service:
     name: "{{ pack }}"   
     state: started